"""
Django settings for skillgap_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v(6carwal_y+2wl7kl=76$um7j^4=_b$uy-@r%l#_snz*9^k0$"


DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "catalog.apps.CatalogConfig",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

}
    
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "skillgap_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "skillgap_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
  'default': {
    'ENGINE':   'django.db.backends.postgresql',
    'NAME':     'skillgap_prod',
    'USER':     'irtiza',
    'PASSWORD': 'StrongP@ssw0rd!',       # or whatever you set at install
    'HOST':     '10.75.1.66',
    'PORT':     '5432',
  }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MAJOR_TO_JOBFIELDS = {
    # 1) School of Arts and Sciences
    "Mass Communication": [
        "Content Writer",
        "Social Media Manager",
        "Public Relations Specialist",
        "Journalist",
        "Media Coordinator",
        "Communications Officer",
    ],
    "Biotechnology": [
        "Biotechnologist",
        "Biomedical Researcher",
        "Quality Control Analyst",
        "Lab Technician",
        "Regulatory Affairs Associate",
        "Biotech Process Engineer",
    ],

    # 2) School of Business
    "Business Administration": [
        "Financial Analyst",
        "Marketing Analyst",
        "HR Specialist",
        "Operations Manager",
        "Business Development Manager",
        "Management Consultant",
        "Supply Chain Analyst",
    ],

    # 3) School of Engineering and Computing
    "Architecture": [
        "Architect",
        "Urban Planner",
        "Landscape Architect",
        "Interior Designer",
        "BIM Coordinator",
    ],
    "Artificial Intelligence": [
        "Machine Learning Engineer",
        "Data Scientist",
        "AI Researcher",
        "NLP Engineer",
        "Computer Vision Engineer",
    ],
    "Chemical Engineering": [
        "Process Engineer",
        "R&D Engineer",
        "Safety Engineer",
        "Quality Control Engineer",
        "Environmental Engineer",
    ],
    "Civil and Infrastructure Engineering": [
        "Structural Engineer",
        "Transportation Engineer",
        "Geotechnical Engineer",
        "Construction Project Engineer",
        "Environmental Engineer",
    ],
    "Computer Engineering": [
        "Embedded Systems Engineer",
        "Hardware Engineer",
        "Firmware Engineer",
        "IoT Engineer",
        "Systems Architect",
    ],
    "Computer Science": [
        "Software Engineer",
        "Backend Developer",
        "Frontend Developer",
        "Full Stack Developer",
        "DevOps Engineer",
        "Data Engineer",
    ],
    "Electrical and Electronics Engineering": [
        "Electronics Engineer",
        "Electrical Design Engineer",
        "Embedded Systems Engineer",
        "Control Systems Engineer",
        "Power Systems Engineer",
    ],
    "Mechanical Engineering": [
        "Mechanical Design Engineer",
        "Manufacturing Engineer",
        "HVAC Engineer",
        "Automotive Engineer",
        "Robotics Engineer",
    ],
}