# Generated by Django 5.2.1 on 2025-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="major",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
