# Generated by Django 5.2.1 on 2025-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_jobfield_alter_concentration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the company offering this job",
                max_length=200,
            ),
        ),
    ]
