# Generated by Django 5.2.1 on 2025-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_jobposting_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="is_paid",
            field=models.BooleanField(
                default=True,
                help_text="Whether taking the certification exam requires payment",
            ),
        ),
    ]
