# Generated by Django 5.2.1 on 2025-06-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_certification_is_paid"),
        ("catalog", "0005_facultyprofile"),
    ]

    operations = []
