# Generated by Django 5.2.1 on 2025-07-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_merge_0005_certification_is_paid_0005_facultyprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("alumni", "Alumni"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="other_job_title",
            field=models.CharField(
                blank=True, help_text="If you selected Other", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_primary",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_secondary",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_work",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="catalog.skill"
            ),
        ),
    ]
