# Generated by Django 5.2.1 on 2025-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_studentprofile_bio_studentprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("major", "Major-Related"),
                    ("technical", "Technical"),
                    ("soft", "Soft"),
                ],
                default="major",
                help_text="Whether this is a major-related, technical, or soft skill",
                max_length=10,
            ),
        ),
    ]
